### PR TITLE
Disk space check / download precentage correction / shutdown process / Players tab & more

### PR DESCRIPTION
**Pull request by Tostifrosti**
In the last months I've been (slowly) updating the Launcher to fix those nagging issues. This PR is a draft because I want to push more fixes in the future. There are a lot of changes, so this way you guys can already look into the recent commits and comment if you see any mistakes.

Changes:
- Download percentage corrections.
- User cancellation improved.
- Installer will keep the downloads after user has interupted the download.
- Overall improvements (added 'using' to dispose some objects after they're done).
- Fixed the shutdown process by stopping all threads before shutdown. (instead of killing the entire application with: Application.Current.Shutdown()).
- Fixed version & username label from being cut off in `UpdateAvailableWindow` & `UsernameWindow`.
- 'BytesPerSecond' bug fixed where the value would go below 0, when downloading update.

New:
- Added interpreter pattern in startup launcher (this makes it easier to add stuff in the future).
- Disk space check before downloading instructions. (Issue #39)
- 'Players' tab added to see currently active players in the server. (Playernames with a prefix '[B]' are seen as bots and will be sorted last in the list.)(Issue: #8)
- Icons added in server selection header.
- Hover effect added on 'Join Server' button.

Removed:
- Removed some unnecessary imports (always good to keep it nice and tidy :D).

Known issues:
- See question 3 from [JAJames](https://github.com/JAJames).
- See question 4 from [JAJames](https://github.com/JAJames).

This PR is related to an [previous pushed PR](https://github.com/TotemArts/Rx_Launcher/pull/41) that hasn’t been merged because of inactivity from my end. I will try to answer/clarify the questions/statements in that PR:

1. [JAJames](https://github.com/JAJames): 
> Validation component exceeding 100% when installing a patch

- This should be fixed in this PR.

2. [JAJames](https://github.com/JAJames): 
> It also seems that anytime I launch the launcher, it prompts to update to the latest version (even if it already is)

- This is my fault and should be fixed in this PR.

3. [JAJames](https://github.com/JAJames): 
> There seems to be a 100% reproducible crash (no error displayed) when you completely lose internet connectivity while attempting to patch/install the game. This is the most significant of the above issues. However, it's not entirely clear if this is caused by these changes, or if it's an existing issue. The crash seems to be caused by us throwing an exception, but never catching it to display to the user.

- If there is any bug/exception in the Launcher during the verify/download/install process, the Launcher will just quit. This was already implemented before my PR. 

4. [JAJames](https://github.com/JAJames): 
> If a mirror is unable to deliver files (i.e: setup a proxy, and start refusing connections mid-install for a specific mirror), the launcher will continue attempting to use that mirror indefinitely. We need to change this behavior such that any mirror which fails the retry strategy is removed from the valid mirror list, so that it's not used for future downloads by the client.

- This bug also existed before my PR. I'll look into this and commit a fix for this in the future.

Of course this PR doesn't fix all the issues, but I'll try my best to work on those issues.
Hopefully you guys will find some time to look the changes ;)
Feel free to comment on any changes below!

### CODE REVIEW

**Comment by SonnyX** [comment]
The PR looks amazing, this might make it to the public.
I do however advice not to spend any further time on this launcher since we are currently working on a new one that is progressing rapidly and addresses many of the issues and feature requests this launcher has.
If you are into helping on the new launcher, please send me a message on Discord.

**Comment by JAJames** [comment]
I'm slamming this through

**Comment by JAJames** [comment]
Except there's a merge conflict

**Comment by Tostifrosti** [comment]
@JAJames 
Merge conflicts resolved ;P

**Comment by SonnyX** [comment]
Closed due to inactivity & deprecation of the current launcher in favor of https://github.com/TotemArts/Launcher/

**Pull request closed without merging**
